// Automatically generated by running `npm run build:snippets`
import JSON5 from 'json5'
const projectId = JSON5.stringify(process.env.NEXT_PUBLIC_SANITY_PROJECT_ID)
const dataset = JSON5.stringify(process.env.NEXT_PUBLIC_SANITY_DATASET)

export function snippet(id: 'theme-import'): (first: string) => string
export function snippet(id: 'studio-config'): (first: string) => string
export function snippet(
  id: 'studio-config-create-theme',
): (first: string) => string
export function snippet(id) {
  switch (id) {
    case 'theme-import':
      return (
        first: string,
      ) => `import {buildThemeFromUrl} from '@sanity/themer/legacy'

const theme = buildThemeFromUrl(${first})`

    case 'studio-config':
      return (first: string) => `// 1. Add the import
import {buildThemeFromUrl} from '@sanity/themer/legacy'

import {defineConfig} from 'sanity'
import {structureTool} from 'sanity/structure'

export default defineConfig({
  // 2. Build the theme from the URL you used to preview it in Themer
  theme: buildThemeFromUrl(${first}),

  projectId: ${projectId},
  dataset: ${dataset},
  plugins: [structureTool()],
  schema: {types: []}
})`

    case 'studio-config-create-theme':
      return (
        first: string,
      ) => `// Read the hues out of the URL to tweak them in code, no need to change the URL

import {createTheme, parseHuesFromUrl} from '@sanity/themer/legacy'
import {defineConfig} from 'sanity'
import {structureTool} from 'sanity/structure'

import {schemaTypes} from './schemas'

const hues = parseHuesFromUrl(${first})

export default defineConfig({
  theme: createTheme({...hues, primary: {...hues.primary, mid: '#22fca8'}}),

  title: 'My Sanity Project',
  projectId: ${projectId},
  dataset: ${dataset},
  plugins: [structureTool()],
  schema: {types: schemaTypes}
})`

    default:
      throw new TypeError('Unknown snippet id: ' + id)
  }
}

export const snippets = [
  'theme-import',
  'studio-config',
  'studio-config-create-theme',
] as const
