// @ts-check
// Compiles snippets so they have prettier formatting pre-applied

import JSON5 from 'json5'
import * as parserBabel from 'prettier/plugins/babel'
// The estree plugin does the actual printing for both the babel and typescript parsers
import * as parserEstree from 'prettier/plugins/estree'
import * as parserTypescript from 'prettier/plugins/typescript'
import * as prettier from 'prettier/standalone'
import writeFileAtomic from 'write-file-atomic'

const options = {
  arrowParens: 'avoid',
  bracketSpacing: false,
  parser: 'typescript',
  plugins: [parserTypescript, parserEstree],
  semi: false,
  singleQuote: true,
  trailingComma: 'none',
}
const jsonOptions = {
  bracketSpacing: false,
  parser: 'json',
  plugins: [parserBabel, parserEstree],
  printWidth: 100,
}

const args = ['first', 'second']
const dummies = {
  // The URL is only a carrier for the hues, `@sanity/themer/legacy` parses it offline
  themerUrl: `/* @dummy */ ${JSON5.stringify('https://example.com/api/hues')}`,
}
const projectId = `'b5vzhxkv'`
const dataset = `'production'`

const snippets = [
  [
    'theme-import',
    ['themerUrl'],
    `
import {buildThemeFromUrl} from '@sanity/themer/legacy'

const theme = buildThemeFromUrl(${dummies.themerUrl})
`,
  ],
  [
    'studio-config',
    ['themerUrl'],
    `
// 1. Add the import
import {buildThemeFromUrl} from '@sanity/themer/legacy'

import { defineConfig } from 'sanity'
import { structureTool } from 'sanity/structure'

export default defineConfig({
  // 2. Build the theme from the URL you used to preview it in Themer
  theme: buildThemeFromUrl(${dummies.themerUrl}),

  projectId: ${projectId},
  dataset:  ${dataset},
  plugins: [structureTool()],
  schema: { types: [],},
})

`,
  ],
  [
    'studio-config-create-theme',
    ['themerUrl'],
    `// Read the hues out of the URL to tweak them in code, no need to change the URL

import {createTheme, parseHuesFromUrl} from '@sanity/themer/legacy'
import { defineConfig } from 'sanity'
import { structureTool } from 'sanity/structure'

import { schemaTypes } from './schemas'

const hues = parseHuesFromUrl(${dummies.themerUrl})

export default defineConfig({
  theme: createTheme({...hues, primary: { ...hues.primary, mid: '#22fca8' } }),

  title: 'My Sanity Project',
  projectId: ${projectId},
  dataset: ${dataset},
  plugins: [structureTool()],
  schema: { types: schemaTypes,},
})

`,
  ],
]

// Sanity check
const idsChecked = new Set()
for (const [id] of snippets) {
  if (idsChecked.has(id)) {
    throw new Error(`Duplicate id: ${id}`)
  }
  idsChecked.add(id)
}

const overloads = []
const getArgs = (argsLength) => {
  const input = args.map((_) => `${_}: string`)
  switch (argsLength) {
    case 1:
      return input[0]
    case 2:
      return [input[0], input[1]].join(', ')
    default:
      return ''
  }
}

const idsList = `export [${[...idsChecked]
  .map((id) => JSON5.stringify(id))
  .join(',')}]`

console.group('snippets.map')
const cases = []
// Sequential so the generated overloads keep the order the snippets are declared in
for (const [id, placeholders, snippet, format = 'typescript'] of snippets) {
  console.group('prettier')
  let code = (
    await prettier.format(snippet, format === 'json' ? jsonOptions : options)
  ).trim()
  console.log(code)
  console.groupEnd()
  // @ts-expect-error -- dunno what to do with the typing of placeholders, maybe try the `const snippets = as const` trick?
  for (const i in placeholders) {
    const key = placeholders[i]
    const dummy = dummies[key]
    const arg = `\${${args[i]}}`
    code = code
      .replaceAll('${', '${"${"}')
      .replaceAll('`', '${"`"}')
      .replaceAll(String.raw`/\/+$/`, `\${${new RegExp(/\/+$/)}}`)
      .replaceAll(dummy, arg)
  }
  console.group('template')
  console.group('dotenv')
  code = code
    .replaceAll(projectId, '${projectId}')
    .replaceAll(dataset, '${dataset}')
  console.groupEnd()

  const { length } = placeholders
  const argsString = getArgs(length)
  const callback = `(${getArgs(length)}) => \`${code}\``
  overloads.push(
    `export function snippet(id: ${JSON5.stringify(
      id,
    )}): ${`(${argsString}) => string`}`,
  )
  const template = `
  case ${JSON5.stringify(id)}:
    return ${callback}
  `
  console.log(template)
  console.groupEnd()
  cases.push(template)
}
console.groupCollapsed()

const codeSnippets = `
// Automatically generated by running \`npm run build:snippets\`
import JSON5 from 'json5'
const projectId = JSON5.stringify(process.env.NEXT_PUBLIC_SANITY_PROJECT_ID)
const dataset = JSON5.stringify(process.env.NEXT_PUBLIC_SANITY_DATASET)

${overloads.join('\n')}
export function snippet(id) {
  switch (id) {
    ${cases.join('\n')}
    default:
      throw new TypeError('Unknown snippet id: ' + id);
  }
}

export const snippets = [${[...idsChecked]
  .map((id) => JSON5.stringify(id))
  .join(',')}] as const;
`

const dest = new URL('../utils/snippets.ts', import.meta.url)
await writeFileAtomic(dest.pathname, codeSnippets)
