name: Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm install --ignore-scripts
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'
      - run: npm run lint
      - run: npm run build
      - run: npm run test --if-present
